### ISSUE TITLE
Vehicle Control Command is missing documentation. What other commands?

### ISSUE THREAD

**Issue by stephendb** [monoDriveIO/documentation#122]
We would like to add a Simulator Control Command page under the Simulator API that documents all the necessary control commands correctly. 

This particular issue was raised because the documentation in the examples specifies the ego control command incorrectly.

**Comment by katiemacaulay** [comment]
Pedro created documentation outline: https://docs.google.com/document/d/1GsABZpxwAlWW-mDyhS3JZW7ErZ5B8rVUloiBO-A82d8/edit
