### ISSUE TITLE
Updated references to lane change trigger boxes 

### ISSUE THREAD

**Issue by bradleynull** [monoDriveIO/documentation#167]
In version 1.11 the lane change trigger box was changed to the "Vehicle Behavior Trigger Box". This needs updating in the RTD and at least something in the notes of the videos for the scenario generation.

![image](https://user-images.githubusercontent.com/6026642/86623708-9df83100-bf87-11ea-8c39-4ddc5ee39f52.png)

**Comment by katiemacaulay** [comment]
resolved with 1.13 pr
