### ISSUE TITLE
The Semantic Camera Values need a paragraph on how to set them on objects in the Editor.

### ISSUE THREAD

**Issue by stephendb** [monoDriveIO/documentation#170]
Add screen shot and some text on how to modify/edit/add the semantic camera value, i.e., set the custom depth stencil value.
https://monodrive.readthedocs.io/en/latest/monoDrive_home/Camera/

**Comment by katiemacaulay** [comment]
@stephendb, I will need more information to add this to the documentation because I am not familiar with how to do this. Would you be able to write up this description or can you recommend someone who can help with this specific task?

**Comment by BrettMonoDrive** [comment]
Add a how to add semantic labels to my doc

https://docs.google.com/document/d/1iljdCm0Qnd2K79vM236mpoWLb_wSeqpb6YmC9m_8JIs/edit?usp=sharing

**Comment by citlaligm** [comment]
Brett, can we add to the this document why we want to add this values? i.e. for the semantic camera to paint the actor correctly, etc?

Also, is the link you have referenced the correct location to the documentation? 
![image](https://user-images.githubusercontent.com/10260895/104200081-d6bd0b00-53ed-11eb-8da3-0afbc9118841.png)

**Comment by BrettMonoDrive** [comment]
Sure I can add a 'why', also the last time I checked that is the spot that has the depth values so the link should be good. But I'll check and see if Katie changed it.

**Comment by BrettMonoDrive** [comment]
The Semantic labeling has been addressed in this document: https://docs.google.com/spreadsheets/d/148UZ8KIqxBZljg8LNLUnIMIKXu5U8upATmI-fUGp2ms/edit?usp=sharing
