### ISSUE TITLE
Add warning to New Vehicle Import/Export Document

### ISSUE THREAD

**Issue by citlaligm** [monoDriveIO/documentation#247]
To avoid other customers to get stuck at not being able to spawn their own model using any client, we should include to this [document ](https://docs.google.com/document/d/1CNKV6uH6LYNShUDCY0I2ScNnKuVzvCVtPHe4Pv_Hcs0/edit) the following:

1. We need to add a warning about the physics volume.
2. Need a picture of skeletal mesh showing where to set the animation.

We need to include a note in the FAQ section too.

**Comment by BrettMonoDrive** [comment]
Added a picture and updated the docs wording on where to apply the animation in the Unreal Blueprint. 

![image](https://user-images.githubusercontent.com/52674907/103931491-fe5a5d80-50e5-11eb-9229-63d626d835f6.png)

**Comment by citlaligm** [comment]
Added to the document.
