### ISSUE TITLE
-opengl instruction on Linux Simulator Build

### ISSUE THREAD

**Issue by katiemacaulay** [monoDriveIO/documentation#272]
![Screenshot from 2021-03-25 15-01-27](https://user-images.githubusercontent.com/41026694/112537558-d4c3e080-8d7c-11eb-8734-b1725fc29f46.png)

Got this error when following the instruction from readthedocs, looks like `-opengl`, is not working with the command to run the simulator. Spoke with Pedro about it, sounds like epic is deprecating support for opengl and using vulcan instead, and the patch for this did not work in the most recent build (1.14). Since UE4 does not want to support opengl any longer, we should consider removing this flag from the Linux build instructions

**Comment by citlaligm** [comment]
closed with #271
